spring:
  application:
    name: annexify-mobile-bff

server:
  port: 8082
  servlet:
    context-path: /api/app

annexify:
  service:
    central:
      url: http://localhost:8080
    storage:
      url: http://localhost:8083
